spring.application.name=bakend



spring.datasource.url=jdbc:mysql://localhost:3306/loja
spring.datasource.username=root
spring.datasource.password=Ailimafa123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
